apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  ports:
    -
      name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
    -
      name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
